# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "HybridgeSample" do
  pod 'Hybridge', :path => '../../../'
end

target "HybridgeSampleTests" do

end

